### PR TITLE
#29 fix(identity): execute registration with retry strategy

### LINKED ISSUE #29: [BUG] InvalidOperationException when registering
```
System.InvalidOperationException: The configured execution strategy 'SqlServerRetryingExecutionStrategy' does not support user-initiated transactions. Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' to execute all the operations in the transaction as a retriable unit.
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.OnFirstExecution()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateUserName(UserManager`1 manager, TUser user)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateAsync(UserManager`1 manager, TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.ValidateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateCoreAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at SmartEventBooking.Infrastructure.Identity.AuthService.RegisterAsync(RegisterDto dto) in /mnt/d/ss/Smart-Event-Booking/src/SmartEventBooking.Infrastructure/Identity/AuthService.cs:line 48
   at SmartEventBooking.Web.Controllers.AuthController.Register(RegisterDto dto) in /mnt/d/ss/Smart-Event-Booking/src/SmartEventBooking.Web/Controllers/AuthController.cs:line 36
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### PR DESCRIPTION
**Pull request by mykhailo-bi**
Wrap user registration in the unit of work execution strategy so transactional identity operations can be retried safely and avoid InvalidOperationException during registration.

Add unit of work support for execution strategies, update auth service to use it, and extend tests to verify the new flow.

Closes #29

### CODE REVIEW

**Comment by mykhailo-bi** [comment]
@mehalyna please accept, bug is fixed

File: src/SmartEventBooking.Infrastructure/Identity/AuthService.cs [hunk 1]
```diff
@@ -34,69 +34,80 @@ public async Task<AuthResultDto> RegisterAsync(RegisterDto dto)
...
             {
-                var appUser = new ApplicationUser
-                {
-                    Id = Guid.NewGuid(),
-                    UserName = dto.Email,
-                    Email = dto.Email
-                };
-
-                var result = await _userManager.CreateAsync(appUser, dto.Password);
+                await _unitOfWork.BeginTransactionAsync();
```
Comment (mehalyna) [inline src/SmartEventBooking.Infrastructure/Identity/AuthService.cs:41]: Nesting BeginTransactionAsync inside ExecuteWithStrategyAsync creates incompatible execution patterns. The retry strategy cannot handle transaction boundaries, causing "The configured execution strategy does not support user-initiated transactions" exception. Either use strategy OR transaction, not both

File: src/SmartEventBooking.Infrastructure/Identity/AuthService.cs [hunk 2]
```diff
@@ -34,69 +34,80 @@ public async Task<AuthResultDto> RegisterAsync(RegisterDto dto)
...
+                }
+
+                return new AuthResultDto { Succeeded = true };
+            });
+
+            if (result.Succeeded && createdUser is not null)
             {
-                _logger.LogError(ex, "An error occurred during registration for user {Email}", dto.Email);
-                throw;
+                await _signInManager.SignInAsync(createdUser, isPersistent: false);
```
Comment (mehalyna) [inline src/SmartEventBooking.Infrastructure/Identity/AuthService.cs:107]: Moving SignInAsync outside the transactional boundary breaks atomicity guarantees. If sign-in fails after commit, the user is registered but not signed in, creating inconsistent state and orphaned records.

File: src/SmartEventBooking.Infrastructure/Persistence/Repositories/UnitOfWork.cs [hunk 3]
```diff
@@ -18,6 +18,16 @@ public async Task<int> SaveChangesAsync(CancellationToken cancellationToken = de
...
     }
 
+    public async Task<TResult> ExecuteWithStrategyAsync<TResult>(Func<Task<TResult>> operation, CancellationToken cancellationToken = default)
+    {
+        var strategy = _context.Database.CreateExecutionStrategy();
+        return await strategy.ExecuteAsync(
+            state: operation,
+            operation: static (_, op, _) => op(),
+            verifySucceeded: null,
+            cancellationToken: cancellationToken);
```
Comment (mehalyna) [inline src/SmartEventBooking.Infrastructure/Persistence/Repositories/UnitOfWork.cs:28]: The static lambda with unused state parameter obscures intent and adds unnecessary complexity. The operation parameter is passed as state but could be invoked directly, violating KISS principle.

**Review by mehalyna — APPROVED** [review]

**Review by eevatsen — APPROVED** [review]

**Comment by mykhailo-bi** [comment]
@mehalyna can you merge please, it's blocking my other pr

**Review by viktorpekhun — APPROVED** [review]
